# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10
    working_directory: ~/wd

    steps:
      - checkout:
          path: ~/wd

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install

      - run:
          name: Make .env file
          command: |
            echo "NODE_PATH=./src/" > ~/wd/.env 


      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # build
      - run: npm run build
      - persist_to_workspace:
          root: /home/circleci/wd
          paths:
            - build/

  publish_artifacts: 
    docker:
    - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: ~/wd
      - run:
          name: Store Service Account JSON (CircleCI env variable to file)
          command: |
            echo $GCLOUD_SERVICE_ACCOUNT > ${HOME}/gcloud-service-key.json
      - run:
          name: Authenticate with Google
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Deploy latest static artifacts in ./build to live bucket
          command: |
            gsutil rsync -d -r ~/wd/build "gs://www.mental-checklist.com"
    
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish_artifacts:
          requires:
            - build
          filters:
            branches:
              only: master
